# Generated by Django 5.0.4 on 2024-04-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Методичка', 'verbose_name_plural': 'Методички'},
        ),
    ]
