# Generated by Django 5.0.6 on 2024-07-09 13:25

import backend.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=backend.main.models.file_upload_path)),
            ],
            options={
                'verbose_name': 'Методичка',
                'verbose_name_plural': 'Методички',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
