# Generated by Django 5.0.6 on 2024-07-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_document_delete_articles_profile_hire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата принятия на работу'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='руководитель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_test_date',
            field=models.DateField(blank=True, null=True, verbose_name='последняя дата прохождения теста'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
