# Generated by Django 5.0.6 on 2024-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='anons',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='document',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
