# Generated by Django 5.0.6 on 2024-07-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_group_groupmembership_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='руководитель'),
        ),
    ]
