# Generated by Django 5.0.6 on 2024-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
