# Generated by Django 5.0.6 on 2024-06-14 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_question_type_alter_question_gfg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedQuestion',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос с развернутым ответом',
                'verbose_name_plural': 'Вопросы с развернутым ответом',
            },
        ),
        migrations.AlterModelOptions(
            name='extendedanswer',
            options={'verbose_name': 'Ответ на вопрос с развернутым ответом', 'verbose_name_plural': 'Ответы на вопросы с развернутым ответом'},
        ),
        migrations.AlterField(
            model_name='question',
            name='gfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfg', to='home.types'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SA', 'Short Answer Question')], default='MCQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='extendedanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.extendedquestion', verbose_name='Вопрос'),
        ),
    ]
