# Generated by Django 5.0.6 on 2024-06-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_extendedquestion_alter_extendedanswer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedanswer',
            old_name='question',
            new_name='question_text',
        ),
    ]
