# Generated by Django 5.0.6 on 2024-06-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_question_extendedanswer_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedquestion',
            name='gfg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extended_questions', to='home.types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendedquestion',
            name='marks',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='gfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.types'),
        ),
    ]
