# Generated by Django 5.0.6 on 2024-06-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extended_question_images/'),
        ),
    ]
