# Generated by Django 5.0.6 on 2024-07-12 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_extendedquestion_difficulty_question_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='extendedanswer',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='extendedanswer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='extendedanswer',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=6, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='gfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_questions', to='home.types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extended_question_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='marks',
            field=models.IntegerField(default=5, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='extendedquestion',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=6, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='question',
            name='gfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=5, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question')], default='MCQ', max_length=3, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_duration',
            field=models.DurationField(verbose_name='Длительность теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(verbose_name='Всего вопросов'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='types',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='types',
            name='gfg_name',
            field=models.CharField(max_length=100, verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='types',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='types',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
