# Generated by Django 5.0.6 on 2024-07-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
