# Generated by Django 4.1.2 on 2024-04-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
