# Generated by Django 5.0.6 on 2024-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
