# Generated by Django 5.0.6 on 2024-06-18 20:33

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_document_options_remove_document_anons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=main.models.file_upload_path),
        ),
    ]
