# Generated by Django 5.0.6 on 2024-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
