# Generated by Django 5.0.6 on 2024-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_hire_date_profile_last_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
