# Generated by Django 5.0.6 on 2024-06-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_profile_manager_profile_is_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Методичка', 'verbose_name_plural': 'Методички'},
        ),
    ]
